version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: football_club_db
    environment:
      POSTGRES_DB: football_club
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secretpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d football_club"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/football_club
      FLYWAY_USER: app
      FLYWAY_PASSWORD: secretpass
    depends_on:
      - postgres

volumes:
  pgdata:
  prometheus_data:
  grafana_data:
